actor:
  _target_: src.sac.model.Actor
  in_channels: ${env.stack_size}
  action_dim: ???
  hidden_dims: [256, 256]

critic:
  _target_: src.sac.model.DoubleCritic
  in_channels: ${env.stack_size}
  action_dim: ???
  hidden_dims: [256, 256]