# DQN configuration as implemented by Minh et al. in "Playing Atari with Deep Reinforcement Learning" (2013).
name: dqn

encoder:
  in_features: 12
  conv_layers:
    - out_features: 16
      kernel_size: 8
      strides: 4
      padding: VALID
    - out_features: 32
      kernel_size: 4
      strides: 2
      padding: VALID
    # Add more layers if needed
    
  fc_layers:
    - in_features: 2592
      out_features: 256
    # Add more layers if needed


