name: rainbow

encoder:
  in_features: 12
  conv_layers:
    - out_features: 16
      kernel_size: 8
      strides: 4
      padding: VALID
    - out_features: 32
      kernel_size: 4
      strides: 2
      padding: VALID
    # Add more layers if needed
    
  fc_layers:
    - in_features: 2592
      out_features: 256
    # Add more layers if needed

atoms: 51
vmin: -10.0
vmax: 10.0
noisy_init_sigma: 0.5