device: auto

# optimizer
lr: 1e-5

# PPO loss
c1: 0.5 # Value loss coefficient
c2: 0.5 # Entropy bonus coefficient
epsilon: 0.2

# steps
rollout_steps: 128
total_frames: 50_000_000

# RL
gamma: 0.99
lam: 0.95
total_frames: 50_000_000

# evaluation
eval_interval: 100_000
eval_episodes: 5

# misc
minibatch_size: 64
num_epochs: 4