device: auto   # auto | cpu | cuda

# model
model:
  actor:
    _target_: src.sac.model.Actor
    in_channels: ${env.stack_size}
    action_dim: ???
    hidden_dims: [256, 256]
  critic:
    _target_: src.sac.model.DoubleCritic
    in_channels: ${env.stack_size}
    action_dim: ???
    hidden_dims: [256, 256]

# optimiser
actor_lr: 3e-4
critic_lr: 3e-4
alpha_lr: 3e-4        # used only if automatic entropy tuning is enabled

# RL
gamma: 0.99
tau: 0.005
total_frames: 10_000_000

# entropy regularisation
alpha: 0.05
auto_alpha: true
target_entropy: null   # if null, use -action_dim

# replay buffer
buffer_size: 300_000
batch_size: 64
start_train_after: 50_000

# network updates
train_every: 1
gradient_steps: 3
target_update_every: 1
max_grad_norm: null

# logging / recording
log_interval_frames: 10_000
eval_interval_frames: 200_000
eval_episodes: 5