defaults:
  - _self_

name: "Hopper-v5"
num_envs: 16

# observation
train_resolution: [120, 120]
full_resolution: [480, 480]
use_luminance: false
stack_size: 4

# action discretisation
action_bins: 5
action_multidiscrete: true   # branching DQN

# reward shaping
use_com_reward: true
forward_reward_weight: 1.0  # Default is 1.0
healthy_reward: 0.1         # Default is 1.0
ctrl_cost_weight: 0.0001     # Default is 0.001.

# env-specific init
healthy_z_range: [0.5, 100.0]     # Default is [0.7, inf]
healthy_angle_range: [-1.0, 1.0]  # Default is [-0.2, 0.2]
reset_noise_scale: 0.005          # Default is 0.005

xml_file: null
