defaults:
  - models@dqn: dqn
  - models@rainbow: rainbow
  - train: base
  - _self_

seed: 42

paths:
  work_dir: ${hydra:runtime.output_dir}
  log_dir: ${paths.work_dir}/logs
  ckpt_dir: ${paths.work_dir}/checkpoints
