defaults:
  - train: dqn
  - model: ${train}        # choose dqn or rainbow
  - env: hopper
  - _self_

seed: 42

paths:
  run_dir: ${hydra:runtime.output_dir}
  log_dir: ${paths.run_dir}/logs
  checkpoint_dir: ${paths.run_dir}/checkpoints
  video_dir: ${paths.run_dir}/videos

hydra:
  run:
    # dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    dir: outputs/run_${now:%Y%m%d_%H%M%S}_${env.name}_${hydra:runtime.choices.train}
    
  job_logging:
    formatters:
      simple:
        format: '[%(levelname)s] - %(message)s' # Removes timestamps and module names